"""Add publish destination column

Revision ID: 0120904b11dd
Revises: ec314d2ad2eb
Create Date: 2026-03-20 21:57:30.955297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0120904b11dd'
down_revision: Union[str, Sequence[str], None] = 'ec314d2ad2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    publishdestination = postgresql.ENUM('feed', 'job_page', 'both', name='publishdestination')
    publishdestination.create(op.get_bind(), checkfirst=True)
    op.add_column('jobs', sa.Column('publish_destination', sa.Enum('feed', 'job_page', 'both', name='publishdestination'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'publish_destination')
    # ### end Alembic commands ###
