"""Add linkedin_cookie support

Revision ID: 038c4ce8b27d
Revises: d236e3318339
Create Date: 2026-03-21 10:31:39.295938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038c4ce8b27d'
down_revision: Union[str, Sequence[str], None] = 'd236e3318339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_cookie', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_cookie')
    # ### end Alembic commands ###
