"""remove_linkedin_email_password

Revision ID: 201f3d04e445
Revises: 038c4ce8b27d
Create Date: 2026-03-21 12:25:14.064260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201f3d04e445'
down_revision: Union[str, Sequence[str], None] = '038c4ce8b27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_password')
    op.drop_column('users', 'linkedin_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedin_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
