"""Add owner_id to jobs

Revision ID: 427decabcf62
Revises: dc189bc0cc6e
Create Date: 2026-03-21 10:00:20.926224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427decabcf62'
down_revision: Union[str, Sequence[str], None] = 'dc189bc0cc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'owner_id')
    # ### end Alembic commands ###
