"""add_candidate_resume_file

Revision ID: 59ea0ec9bdc8
Revises: 0204ff87c3b9
Create Date: 2026-03-22 04:04:52.254204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ea0ec9bdc8'
down_revision: Union[str, Sequence[str], None] = '0204ff87c3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_base64', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('resume_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_filename')
    op.drop_column('candidates', 'resume_base64')
    # ### end Alembic commands ###
