"""Add ATS fields to Job and Candidate

Revision ID: 6735da93867f
Revises: 59ea0ec9bdc8
Create Date: 2026-03-22 15:11:57.098176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6735da93867f'
down_revision: Union[str, Sequence[str], None] = '59ea0ec9bdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('ats_score', sa.Numeric(), nullable=True))
    op.add_column('candidates', sa.Column('ats_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('skill_weight', sa.Numeric(), nullable=True))
    op.add_column('jobs', sa.Column('experience_weight', sa.Numeric(), nullable=True))
    op.add_column('jobs', sa.Column('education_weight', sa.Numeric(), nullable=True))
    op.add_column('jobs', sa.Column('keyword_weight', sa.Numeric(), nullable=True))
    op.add_column('jobs', sa.Column('shortlist_threshold', sa.Numeric(), nullable=True))
    op.add_column('jobs', sa.Column('review_threshold', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'review_threshold')
    op.drop_column('jobs', 'shortlist_threshold')
    op.drop_column('jobs', 'keyword_weight')
    op.drop_column('jobs', 'education_weight')
    op.drop_column('jobs', 'experience_weight')
    op.drop_column('jobs', 'skill_weight')
    op.drop_column('candidates', 'ats_explanation')
    op.drop_column('candidates', 'ats_score')
    # ### end Alembic commands ###
