"""Add user preferences

Revision ID: 7293838bb30e
Revises: 427decabcf62
Create Date: 2026-03-21 10:05:51.433501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7293838bb30e'
down_revision: Union[str, Sequence[str], None] = '427decabcf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_platform', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_destination', sa.Enum('feed', 'job_page', 'both', name='publishdestination', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_destination')
    op.drop_column('users', 'preferred_platform')
    op.alter_column('jobs', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
