"""Add user platform credentials

Revision ID: d236e3318339
Revises: 7293838bb30e
Create Date: 2026-03-21 10:11:06.353165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd236e3318339'
down_revision: Union[str, Sequence[str], None] = '7293838bb30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('linkedin_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_password')
    op.drop_column('users', 'linkedin_email')
    op.alter_column('jobs', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
