"""add interview_type to InterviewSession

Revision ID: e60787fed7c1
Revises: 9d4fb8971e73
Create Date: 2026-03-25 21:41:28.726860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60787fed7c1'
down_revision: Union[str, Sequence[str], None] = '9d4fb8971e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PHONE', 'WEB', name='interviewtype').create(op.get_bind())
    op.add_column('interview_sessions', sa.Column('interview_type', sa.Enum('PHONE', 'WEB', name='interviewtype'), nullable=True))
    op.execute("UPDATE interview_sessions SET interview_type = 'PHONE'")
    op.alter_column('interview_sessions', 'interview_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'interview_type')
    sa.Enum('PHONE', 'WEB', name='interviewtype').drop(op.get_bind())
    # ### end Alembic commands ###
