"""add_cookie_expired_to_user

Revision ID: e765a5ac79d7
Revises: 201f3d04e445
Create Date: 2026-03-21 12:39:54.843205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e765a5ac79d7'
down_revision: Union[str, Sequence[str], None] = '201f3d04e445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_cookie_expired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_cookie_expired')
    # ### end Alembic commands ###
