"""Add linkedin fields

Revision ID: ec314d2ad2eb
Revises: ad7e283cb551
Create Date: 2026-03-20 10:37:28.020519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec314d2ad2eb'
down_revision: Union[str, Sequence[str], None] = 'ad7e283cb551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    publishstatus = postgresql.ENUM('pending', 'published', 'failed', name='publishstatus')
    publishstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('jobs', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('publish_status', sa.Enum('pending', 'published', 'failed', name='publishstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'publish_status')
    op.drop_column('jobs', 'linkedin_url')
    from sqlalchemy.dialects import postgresql
    publishstatus = postgresql.ENUM('pending', 'published', 'failed', name='publishstatus')
    publishstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
