"""Add image and tags columns

Revision ID: efdbf3dc94e4
Revises: 0120904b11dd
Create Date: 2026-03-20 22:07:14.236045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdbf3dc94e4'
down_revision: Union[str, Sequence[str], None] = '0120904b11dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_base64', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'tags')
    op.drop_column('jobs', 'image_base64')
    # ### end Alembic commands ###
