"""add_user_id_to_publication

Revision ID: f205cdd33859
Revises: e765a5ac79d7
Create Date: 2026-03-22 01:26:56.146665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f205cdd33859'
down_revision: Union[str, Sequence[str], None] = 'e765a5ac79d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'publications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_column('publications', 'user_id')
    # ### end Alembic commands ###
